### ISSUE TITLE
Ability to detect WAF block by response data

### ISSUE THREAD

**Issue by roisec** [fastly/wafefficacy#22]
Hi, 
I think is it a good initiative around the WAF test framework! good work!
Can you add please the option to detect blocking by HTTP response data?
for example, if WAF is able to return 200 OK with the content "This request was blocked by the security rules"
It is possible through Nuclei.

**Comment by skhalsa-sigsci** [comment]
I think the option you are looking for is `-r  (optional) custom waf response, defaults to 406 Not Acceptable`. When you run the efficacy tests, your command should look something like this `./run.sh -t example.com -r "This request was blocked by the security rules"`
